environment:
  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python27"

    # Python 3.3 has reached EOL

install:
  # Prepend Python installation to PATH
  - set PATH=%PYTHON_INSTALL%;%PATH%

  # Prepend Python scripts to PATH (e.g. py.test)
  - set PATH=%PYTHON_INSTALL%\\Scripts;%PATH%

  # We need to install the python-can library itself
  - "python -m pip install .[test,neovi]"

build: off

before_test:
  # see: https://help.appveyor.com/discussions/problems/938-getting-permission-denied-errors-when-trying-to-make-a-temp-directory
  # TMPDIR is used by Python to detect the temporary directory: https://docs.python.org/3/library/tempfile.html#tempfile.tempdir
  - set TMPDIR=%APPVEYOR_BUILD_FOLDER%\test\__tmpdir__
  - mkdir %TMPDIR%
  - icacls %TMPDIR% /inheritance:r /grant Everyone:F

test_script:
  - "pytest"
  - "codecov"

after_test:
  - rmdir /S /Q %TMPDIR%

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
